/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessibilityMenu: typeof import('./src/components/AccessibilityMenu.vue')['default']
    ClientServices: typeof import('./src/components/ClientServices.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeaderNavigation: typeof import('./src/components/HeaderNavigation.vue')['default']
    InstitutionalSite: typeof import('./src/components/InstitutionalSite.vue')['default']
    OfficeMap: typeof import('./src/components/OfficeMap.vue')['default']
    PracticeAreas: typeof import('./src/components/PracticeAreas.vue')['default']
    ProfessionalPage: typeof import('./src/components/ProfessionalPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamSection: typeof import('./src/components/TeamSection.vue')['default']
  }
}
